"""Add financial data and cache tables

Revision ID: 2c20b8027f74
Revises:
Create Date: 2025-07-31 23:30:16.327360

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c20b8027f74"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_name", sa.String(), nullable=True),
        sa.Column("request_key", sa.String(), nullable=True),
        sa.Column("response_data", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_cache_api_name"), "api_cache", ["api_name"], unique=False)
    op.create_index(op.f("ix_api_cache_id"), "api_cache", ["id"], unique=False)
    op.create_index(op.f("ix_api_cache_request_key"), "api_cache", ["request_key"], unique=False)
    op.create_index(op.f("ix_api_cache_timestamp"), "api_cache", ["timestamp"], unique=False)
    op.create_table(
        "stock_predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("analysis", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("estimated_change", sa.Float(), nullable=True),
        sa.Column("eps", sa.Float(), nullable=True),
        sa.Column("pe_ratio", sa.Float(), nullable=True),
        sa.Column("revenue", sa.Float(), nullable=True),
        sa.Column("net_income", sa.Float(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stock_predictions_id"), "stock_predictions", ["id"], unique=False)
    op.create_index(
        op.f("ix_stock_predictions_published_at"),
        "stock_predictions",
        ["published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_predictions_symbol"), "stock_predictions", ["symbol"], unique=False
    )
    op.create_index("ix_symbol_date", "stock_predictions", ["symbol", "published_at"], unique=False)
    op.drop_table("predictions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "predictions",
        sa.Column("symbol", sa.TEXT(), nullable=True),
        sa.Column("date", sa.TEXT(), nullable=True),
        sa.Column("percent_estimate", sa.REAL(), nullable=True),
        sa.Column("explanation", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "date"),
    )
    op.drop_index("ix_symbol_date", table_name="stock_predictions")
    op.drop_index(op.f("ix_stock_predictions_symbol"), table_name="stock_predictions")
    op.drop_index(op.f("ix_stock_predictions_published_at"), table_name="stock_predictions")
    op.drop_index(op.f("ix_stock_predictions_id"), table_name="stock_predictions")
    op.drop_table("stock_predictions")
    op.drop_index(op.f("ix_api_cache_timestamp"), table_name="api_cache")
    op.drop_index(op.f("ix_api_cache_request_key"), table_name="api_cache")
    op.drop_index(op.f("ix_api_cache_id"), table_name="api_cache")
    op.drop_index(op.f("ix_api_cache_api_name"), table_name="api_cache")
    op.drop_table("api_cache")
    # ### end Alembic commands ###
