"""Add HistoricalImpact table

Revision ID: 897acbdabb2a
Revises: 2c20b8027f74
Create Date: 2025-08-01 00:47:27.751113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "897acbdabb2a"
down_revision: Union[str, Sequence[str], None] = "2c20b8027f74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historical_impacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("news_title", sa.String(), nullable=True),
        sa.Column("news_date", sa.DateTime(), nullable=True),
        sa.Column("price_before", sa.Float(), nullable=True),
        sa.Column("price_after", sa.Float(), nullable=True),
        sa.Column("impact_percentage", sa.Float(), nullable=True),
        sa.Column("sentiment", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_historical_impacts_id"), "historical_impacts", ["id"], unique=False)
    op.create_index(
        op.f("ix_historical_impacts_news_date"),
        "historical_impacts",
        ["news_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_impacts_symbol"),
        "historical_impacts",
        ["symbol"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_historical_impacts_symbol"), table_name="historical_impacts")
    op.drop_index(op.f("ix_historical_impacts_news_date"), table_name="historical_impacts")
    op.drop_index(op.f("ix_historical_impacts_id"), table_name="historical_impacts")
    op.drop_table("historical_impacts")
    # ### end Alembic commands ###
