"""Add AI scoring fields to StockPrediction

Revision ID: cb27903fb7d9
Revises: 897acbdabb2a
Create Date: 2025-08-04 04:20:24.903683

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb27903fb7d9"
down_revision: Union[str, Sequence[str], None] = "897acbdabb2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stock_predictions", sa.Column("probability", sa.Float(), nullable=True))
    op.add_column("stock_predictions", sa.Column("reward_to_risk", sa.Float(), nullable=True))
    op.add_column("stock_predictions", sa.Column("recommendation", sa.String(), nullable=True))
    op.add_column("stock_predictions", sa.Column("ai_full_text", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_predictions", "ai_full_text")
    op.drop_column("stock_predictions", "recommendation")
    op.drop_column("stock_predictions", "reward_to_risk")
    op.drop_column("stock_predictions", "probability")
    # ### end Alembic commands ###
